plugins {
    id 'java'
}

group = 'com.gregross.bitwig'
version = '0.1.0'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
    maven {
        url 'https://maven.bitwig.com'
    }
}

dependencies {
    implementation 'com.bitwig:extension-api:22'
}

jar {
    archiveFileName = 'LaunchpadMk2.bwextension'
}

tasks.register('install', Copy) {
    description = 'Installs the extension to the Bitwig Studio Extensions directory'
    from jar
    into project.property('bitwigExtensionsDir')
}
